# Generated by Django 3.2.5 on 2021-12-13 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Valsinaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicidad',
            name='telefono',
            field=models.IntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicidad',
            name='web',
            field=models.CharField(default=2001, max_length=80),
            preserve_default=False,
        ),
    ]
