# Generated by Django 3.2.5 on 2021-09-05 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comercio',
            new_name='Negocio',
        ),
        migrations.AlterModelOptions(
            name='negocio',
            options={'verbose_name': 'negocio', 'verbose_name_plural': 'negocios'},
        ),
    ]
