# Generated by Django 3.2.5 on 2021-09-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0002_auto_20210905_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Negocio',
        ),
    ]
