# Generated by Django 3.2.5 on 2021-09-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0004_negocio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='nombre',
            new_name='nombreneg',
        ),
    ]
