# Generated by Django 3.2.5 on 2021-12-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0005_rename_nombre_negocio_nombreneg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comercioimg'),
        ),
    ]
