# Generated by Django 3.2.5 on 2021-12-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0006_alter_negocio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='slogan',
            field=models.CharField(max_length=140),
        ),
    ]
